jobs:
  check-up-to-date-action-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v26
      with:
        extra_nix_config: accept-flake-config = true
    - uses: cachix/cachix-action@v14
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        name: nickel-schemastore
    - name: Check that the generated action files match the Nickel source
      run: |-
        nix run .#regenerate-files -L
        git diff --exit-code
on:
  push: {}
