jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v26
      with:
        extra_nix_config: accept-flake-config = true
    - uses: cachix/cachix-action@v14
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        name: nickel-schemastore
    - name: Ensure that schema files don't need a rebuild
      run: |-
        nix develop --command python3 ./extract-schemas.py
        git diff --exit-code
on: push
